storeFile = ClimbingRecord.jks
storePassword = ClimbingRecord20231206
keyAlias = ClimbingRecord
keyPassword = ClimbingRecord20231206
APP_CHECK_DEBUG_TOKEN_FROM_CI = 87689ac5-8dd9-49c1-a2a7-b414f808689d